services:
  db:
    image: "postgres:16.3"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  back:
    image: "node:22-alpine3.19"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: "npm i"
    entrypoint: ["npm", "run", "dev"]
    depends_on:
      db:
        condition: service_healthy
volumes:
  db: